#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: MIT

USE_PROCD=1
START=95
STOP=10

start_service() {
	local enabled

	config_load newt
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/libexec/newt-run
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_set_param file /etc/config/newt
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger newt
	procd_add_raw_trigger "interface.*.up" 3000 /etc/init.d/newt restart
}

