# SPDX-License-Identifier: MIT

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pangolin-newt
PKG_VERSION:=1.16.0
PKG_RELEASE:=2
LUCI_TITLE:=LuCI support for Pangolin Newt
LUCI_DEPENDS:=+luci-base +pangolin-newt
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
